# src/daily_summary_report.py
"""
GeoClimate AI - Daily Climate Risk Summary Email System (Phase 9.5)
Generates daily summary of IoT data & alerts, attaches CRI chart, and emails report.
"""

import os
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
from datetime import datetime, timedelta
import json
import io
import base64

# Load email config
CONFIG_PATH = "src/config_email.json"
with open(CONFIG_PATH, "r") as f:
    cfg = json.load(f)

DB_PATH = "data/climate_ai.db"

def fetch_recent_data(hours=24):
    """Fetch last N hours of IoT and alerts data."""
    conn = sqlite3.connect(DB_PATH)
    since_time = (datetime.utcnow() - timedelta(hours=hours)).strftime("%Y-%m-%d %H:%M:%S")
    iot = pd.read_sql(f"SELECT * FROM iot_data WHERE timestamp >= '{since_time}'", conn)
    alerts = pd.read_sql(f"SELECT * FROM alerts WHERE timestamp >= '{since_time}'", conn)
    conn.close()
    return iot, alerts

def generate_summary_plot(iot_df):
    """Generate a CRI trend plot and return base64-encoded PNG."""
    if iot_df.empty:
        return None
    plt.figure(figsize=(8, 4))
    iot_df['timestamp'] = pd.to_datetime(iot_df['timestamp'])
    avg_cri = iot_df.groupby('timestamp')['cri'].mean().reset_index()
    plt.plot(avg_cri['timestamp'], avg_cri['cri'], marker='o')
    plt.title("Average CRI (Last 24 Hours)")
    plt.xlabel("Time")
    plt.ylabel("CRI")
    plt.grid(True)
    buf = io.BytesIO()
    plt.tight_layout()
    plt.savefig(buf, format='png')
    buf.seek(0)
    encoded = base64.b64encode(buf.read()).decode('utf-8')
    plt.close()
    return encoded

def create_html_report(iot, alerts, plot_b64):
    """Create HTML body for the email."""
    total_cities = len(iot['city'].unique()) if not iot.empty else 0
    avg_cri = round(iot['cri'].mean(), 2) if not iot.empty else 0
    max_cri = round(iot['cri'].max(), 2) if not iot.empty else 0
    top_cities = (
        iot.groupby('city')['cri'].mean()
        .sort_values(ascending=False)
        .head(3)
        .reset_index()
        if not iot.empty else pd.DataFrame(columns=['city', 'cri'])
    )

    html = f"""
    <h2>🌍 GeoClimate AI - Daily Climate Risk Summary</h2>
    <p><b>Date:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
    <ul>
      <li><b>Total Cities Monitored:</b> {total_cities}</li>
      <li><b>Average CRI:</b> {avg_cri}</li>
      <li><b>Max CRI:</b> {max_cri}</li>
      <li><b>Total Alerts:</b> {len(alerts)}</li>
    </ul>
    """

    if not top_cities.empty:
        html += "<h3>🔥 Top 3 Risky Cities</h3><ol>"
        for _, row in top_cities.iterrows():
            html += f"<li>{row['city']} — CRI: {round(row['cri'], 2)}</li>"
        html += "</ol>"

    if plot_b64:
        html += f"<img src='data:image/png;base64,{plot_b64}' alt='CRI Chart'/>"

    if not alerts.empty:
        html += "<h3>🚨 Recent Alerts</h3><ul>"
        for _, row in alerts.iterrows():
            html += f"<li>{row['timestamp']} — {row['city']} ({row['level']}) — CRI: {row['cri']}</li>"
        html += "</ul>"

    html += "<br><p>Report auto-generated by GeoClimate AI.</p>"
    return html

def send_summary_email():
    iot, alerts = fetch_recent_data(24)
    plot_b64 = generate_summary_plot(iot)
    html_body = create_html_report(iot, alerts, plot_b64)

    sender = cfg["sender_email"]
    password = cfg["sender_password"]
    receiver = cfg["receiver_email"]

    msg = MIMEMultipart("related")
    msg["From"] = sender
    msg["To"] = receiver
    msg["Subject"] = f"🌤️ GeoClimate AI - Daily Climate Risk Summary ({datetime.utcnow().strftime('%b %d')})"
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(cfg["smtp_host"], cfg["smtp_port"]) as server:
            server.starttls()
            server.login(sender, password)
            server.send_message(msg)
        print("✅ Daily summary email sent successfully!")
    except Exception as e:
        print("❌ Failed to send summary email:", e)

if __name__ == "__main__":
    send_summary_email()
